apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-ceph
  namespace: openreplay
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-dm-cephfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-ceph
  namespace: openreplay
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-dm-cephfs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-ceph
  namespace: openreplay
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-dm-cephfs
  resources:
    requests:
      storage: 5Gi
