# Applica su Rancher:
#   kubectl apply -f gitrepo.yaml -n fleet-default
#
# Oppure crea dall'UI: Continuous Delivery > Git Repos > Add Repository
#
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: openreplay
  namespace: fleet-default
spec:
  repo: https://github.com/dm-italy/openreplay.git
  branch: deploy/rancher-fleet
  # Se repo privato:
  # clientSecretName: git-credentials
  paths:
    - scripts/helmcharts/databases
    - scripts/helmcharts/openreplay
  targets:
    - clusterSelector: {}
