apiVersion: v1
kind: Namespace
metadata:
  name: openreplay
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openreplay-shared-storage
  namespace: openreplay
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-dm-cephfs
  resources:
    requests:
      storage: 5Gi
